travis:
  secure:
    BINSTAR_TOKEN: auhlf31K+qE7QTUtpp8JS4v8Y1KSRfsVf4LGedVnf5XlAUKoktMnm35kzI3+5Dx+nowSBl7YDRx9o7nOuSh+vkQr6TnrrRbenlRqHg9KIfKk+oSu8zdR1FwXYLYMz3CPIM13uZsesOQ/NcVJXMNiODnUw+VAk4goebEZgHPpNJXLlbsIK26oKucTpNMtWKD+EOc5Z6tcoJjG4a6ISXpCUbtbljlbjocNPDs4pFotY2OTJZvV634JLwZsBROUzZj9m20Mqkh1DLRz/wyEfE1HOLZbqJT9/RK0Tb1fCiIjnlcTgVA54Bbwv1yCdy6CeMabmJEP81SrqPNXzg2F31ErqiwTe0+0a0W+FLa/gJnoZ2MuSt5qiMs8iQ7gkI9ceGxMjqcIE9jjlxqv8rlHtOd2bo/MjSa9pa3VclL0UMxIq4xpFZb423R9iBOcNX171bOhm4H3f5OLisgkiSEc9RRt8TXp/rg1mhPI5B7ZLggg0pjy+Lvn2lFnAgfTn6YEZVUKzYeHyGqFlMhge+FMQ04nMu1Y2y+ZYB1IecPA9r1EfTy1o7Qj+EcwwZEhTyQAd2W9+5pzpCxqpdd2b6cjQSKunum+bPtN+W9J1Vcyi1gp1cJjx2YgMDUjSeVKui+4l+cbqfK7IhvmbWry4oGqdohfpIUdTd5Hc+lue59fW/X4e4s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
