travis:
  secure:
    BINSTAR_TOKEN: gk7K+XL5GnWYVt388z2F9LEUe23y3q5KrO28QsbvEL84BsN8qfsmCynVpjmNwwTBdsjK/2jnFXHsUcoq68qjYIS5iUB7/3zsSD9eJLlxdC5k152Pc/HjHMq+5u9hJFbfPXbjxupk+bfvxPUJZdmLJ/zW3Rq2IdPJNLfKNkHj1HFTRFceoj41K87ZAzs1caIzFR+iWArbZc92aX7e1GECOiXLXeNNww0o7Pekjsp/bffrnUhbme5HC6miOZH0PClBPbM1kMXCEIFOLaVTt6bpup6Vd2lxDRlinGLT3WJiWEIaupcH9cVOQQVCmHFXa4BkfMN/ossmmAMrp/UM6xcpcdMLANXMWvkw/42Hz60bujxb05hH7asI6s+7/V9+8gQfxFbzOWeyEw5TRg9kCJtJ1+YvUMdqXK1/NJKtzkExKS8Aa6cCamUPeg8mOE8Bl7v79oFOYCjtaJeZeTt0m1zFa9IRfdopB1e6Jp9LPqrAUnKCfIWbSRnEHuKT+LcP/iMy7TZyvUAGDHT2ZyyrlOKC3xscULaFtbd0ojzm8/0j8Z3KCxI+MUJHYgHZf2gHNbQLtORycGIVqj+Xf6QnKceoiGrtz7RauskbzR2xYH0LZmNEZyfzB9VYKBz5TvALK+XtASh8J3vm9T1MZE+XmL1BV4V6sCT7/aQJWwrBG8Z7F08=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
